import globals from 'globals';
import noUnsanitized from 'eslint-plugin-no-unsanitized';

export default [
  {
    files: ['**/*.js'],
    linterOptions: {
      reportUnusedDisableDirectives: 'off',
    },
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        // Vitest globals (테스트 파일 전용 fallback)
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeAll: 'readonly',
        beforeEach: 'readonly',
        afterAll: 'readonly',
        afterEach: 'readonly',
        vi: 'readonly',
        // External CDN / browser extension globals (Phase 5: KEEP — 외부 진입점)
        chrome: 'readonly',
        pdfjsLib: 'readonly',
        XLSX: 'readonly',
        ChannelIO: 'readonly',
        QRCode: 'readonly',
        gtag: 'readonly',
        Tesseract: 'readonly',
        // pay-estimation.js IIFE 내부 정의 — window 등록되어 cross-file 접근
        PayrollImprovementAgent: 'readonly',
        calcMonthEstimate: 'readonly',
        // profile-tab.js 정의 — work-history.js 가 자동 시드 호출
        _seedFirstWorkFromProfile: 'readonly',
        _collapseBasicFieldsWithPreview: 'readonly',
        // KEEP allowlist — HTML inline onclick 으로 호출되는 함수들 (cross-file 노출 보존)
        // index.html / public/tabs/*.html 의 inline onclick 에서 참조 — 이중 정의 방지용 declare
        switchTab: 'readonly',
        switchProfileSection: 'readonly',
        switchHomePeriod: 'readonly',
        switchNewsTab: 'readonly',
        initProfileTab: 'readonly',
        initLeaveTab: 'readonly',
        initPayrollTab: 'readonly',
        initHomeTab: 'readonly',
        initOvertimeTab: 'readonly',
        initRetirementTab: 'readonly',
        initPayEstimate: 'readonly',
        initBrowse: 'readonly',
        initSubTabs: 'readonly',
        initTheme: 'readonly',
        initPdfSheet: 'readonly',
        applyProfileToOvertime: 'readonly',
        applyProfileToLeave: 'readonly',
        applyProfileToPayroll: 'readonly',
        applyPromotionDate: 'readonly',
        clearProfile: 'readonly',
        downloadBackup: 'readonly',
        saveProfile: 'readonly',
        saveOtRecord: 'readonly',
        saveLvRecord: 'readonly',
        saveResumeItem: 'readonly',
        saveWorkHistoryEntry: 'readonly',
        saveRotationEntry: 'readonly',
        deleteOtRecord: 'readonly',
        deleteLvRecord: 'readonly',
        deleteRotationEntry: 'readonly',
        deleteWorkHistoryEntry: 'readonly',
        editOtRecord: 'readonly',
        renderWorkHistory: 'readonly',
        renderResumeSections: 'readonly',
        renderQuickTags: 'readonly',
        renderPayslip: 'readonly',
        renderPayslipMgmt: 'readonly',
        renderPayPayslip: 'readonly',
        renderLeaveTable: 'readonly',
        renderCeremonyTable: 'readonly',
        renderVerification: 'readonly',
        refreshLvCalendar: 'readonly',
        toggleCollapsible: 'readonly',
        toggleChildFields: 'readonly',
        toggleOtHelp: 'readonly',
        toggleOtHelpDetail: 'readonly',
        toggleOtVerifyDetail: 'readonly',
        toggleUnder6Field: 'readonly',
        updateProfileGrades: 'readonly',
        updatePayrollGrades: 'readonly',
        updateGrades: 'readonly',
        updateAppLockUI: 'readonly',
        updateProfileSummary: 'readonly',
        updateProfileTitle: 'readonly',
        updateFamilyUI: 'readonly',
        updateQuickActionPrices: 'readonly',
        populateJobTypeDropdowns: 'readonly',
        populateLvTypeSelect: 'readonly',
        autoFillMonth: 'readonly',
        autofillJobDesc: 'readonly',
        autofillRotationTasks: 'readonly',
        openWorkHistorySheet: 'readonly',
        openLvBottomSheet: 'readonly',
        openLvTypeBottomSheet: 'readonly',
        openOtBottomSheet: 'readonly',
        openRotationSheet: 'readonly',
        openAddWorkHistoryPicker: 'readonly',
        openMilitarySheet: 'readonly',
        closeMigrationModal: 'readonly',
        closeLvBottomSheet: 'readonly',
        closeLvTypeBottomSheet: 'readonly',
        closeOtBottomSheet: 'readonly',
        closeWorkHistorySheet: 'readonly',
        closeRotationSheet: 'readonly',
        closeResumeItemSheet: 'readonly',
        closePdfSheet: 'readonly',
        closeCalloutModal: 'readonly',
        showWikiCategory: 'readonly',
        showVerifyInQna: 'readonly',
        searchHandbook: 'readonly',
        searchBrowse: 'readonly',
        searchChat: 'readonly',
        clearWikiSearch: 'readonly',
        scrollChapterTabs: 'readonly',
        scrollToOtGroup: 'readonly',
        scrollToBottom: 'readonly',
        scrollToNextSection: 'readonly',
        retSelectPeakOpt: 'readonly',
        retSetRetireDate: 'readonly',
        retToggleRateCard: 'readonly',
        retUpdateQuickDates: 'readonly',
        retGetRateForYears: 'readonly',
        retGetSeveranceRate: 'readonly',
        retFmt: 'readonly',
        retFmtDate: 'readonly',
        retToInputDate: 'readonly',
        renderRetSimTimeline: 'readonly',
        renderRetirementTimeline: 'readonly',
        calcRetirementEmbedded: 'readonly',
        calcScenarioEmbedded: 'readonly',
        calculateLeave: 'readonly',
        calculateNightBonus: 'readonly',
        calculateOnCall: 'readonly',
        calculateOvertime: 'readonly',
        calculateParentalLeave: 'readonly',
        calculateSeverance: 'readonly',
        calculateWage: 'readonly',
        calculatePayroll: 'readonly',
        previewOtCalc: 'readonly',
        previewLvCalc: 'readonly',
        previewCalloutCalc: 'readonly',
        applyOtTimePreset: 'readonly',
        quickOtCallout: 'readonly',
        quickOtRecord: 'readonly',
        saveCalloutRecord: 'readonly',
        otNavMonth: 'readonly',
        otGoToday: 'readonly',
        lvNavMonth: 'readonly',
        lvGoToday: 'readonly',
        onLvDateClick: 'readonly',
        onLvTypeChange: 'readonly',
        onOtDateClick: 'readonly',
        onOtTypeChange: 'readonly',
        onOtHourlyInput: 'readonly',
        onAppLockChangePin: 'readonly',
        onAppLockDisable: 'readonly',
        onAppLockSetupPin: 'readonly',
        onBiometricDisable: 'readonly',
        onBiometricRegister: 'readonly',
        editLvRecord: 'readonly',
        selectLvType: 'readonly',
        selectOtRecordTab: 'readonly',
        selectOtNewTab: 'readonly',
        importOtData: 'readonly',
        importLvData: 'readonly',
        exportOtData: 'readonly',
        exportLvData: 'readonly',
        switchToProfileTab: 'readonly',
        switchPayrollSubTab: 'readonly',
        startTutorial: 'readonly',
        autoSelectToday: 'readonly',
        printResume: 'readonly',
        shareApp: 'readonly',
        downloadTeamScheduleIcs: 'readonly',
        dismissHwBanner: 'readonly',
        deleteRotation: 'readonly',
        addRotation: 'readonly',
        updateRotation: 'readonly',
        acceptSeededWorkHistory: 'readonly',
        downloadBackupAndStay: 'readonly',
        exitDemoMode: 'readonly',
        goToApp: 'readonly',
        nextStep: 'readonly',
        prevStep: 'readonly',
        renderStep: 'readonly',
        loadEmbeds: 'readonly',
        pdfNextPage: 'readonly',
        pdfPrevPage: 'readonly',
        pdfZoom: 'readonly',
        showOtToast: 'readonly',
        SALARY_TEST: 'readonly',
        importScripts: 'readonly',
        BhmAuth: 'readonly',
        BhmDrive: 'readonly',
        BhmStorage: 'readonly',
        LoginScreen: 'readonly',
        PinSetupScreen: 'readonly',
        PinScreen: 'readonly',
        OvertimeScreen: 'readonly',
        LeaveScreen: 'readonly',
        PdfScreen: 'readonly',
        SettingsScreen: 'readonly',
        calcLeaveDays: 'readonly',
        calcTimeBreakdown: 'readonly',
        // Phase 5 노트: 위 globals 는 HTML inline onclick / cross-file dispatch 에서 호출되는 함수들로,
        // 모듈 간 사용은 named import 으로 전환 완료 — 이 globals 는 ESLint no-undef 노이즈 방지용.
      },
    },
    plugins: {
      'no-unsanitized': noUnsanitized,
    },
    rules: {
      'no-undef': 'error',
      'no-unsanitized/property': 'off',
      'no-unused-vars': 'off',
      'no-redeclare': 'off',
      'no-empty': 'off',
      'no-constant-condition': 'off',
      'no-prototype-builtins': 'off',
    },
  },
  {
    ignores: [
      'dist/**',
      'apps/web/dist/**',
      'node_modules/**',
      'archive/**',
      'public/legacy/**',
      'shorts-studio/**',
      'public/admin/**',
      'apps/web/public/admin/**',
      'public/sw.js',
      'public/data/**',
      'public/tabs/**',
      '.worktrees/**',
      '.claude/**',
      'ops/**',
    ],
  },
];
